In [1]:
import pandas as pd
import numpy as np
from statistics import mean

In [15]:
print("Loading dataframe")
training = pd.read_pickle('training.pkl')
test = pd.read_pickle('test.pkl')

Loading dataframe

In [3]:
columns = list(training.columns)
columns

['Actor1',
 'Actor2',
 'Actor3',
 'Country',
 'Customer_ID',
 'Director1',
 'Director2',
 'Genre1',
 'Genre2',
 'Genre3',
 'Language',
 'Movie_ID',
 'Production_Company',
 'Title',
 'Writer1',
 'Writer2',
 'Year',
 'Duration',
 'Rating']

In [16]:
training = training.fillna(3)
test = test.fillna(3)

In [5]:
# Calculate the values of each attribution

# Actors
actors_map = {}
actors_map[3] = 3

unique_actors = pd.unique(training[['Actor1', 'Actor2','Actor3']].to_numpy().ravel())
for actor in unique_actors:
  filtered_df = training[(training['Actor1']==actor) | (training['Actor2']==actor) | (training['Actor3']==actor)]
  actor_rating = filtered_df['Rating'].values.mean()
  actors_map[actor] = actor_rating

# Country
country_map = {}
country_map[3] = 3

unique_countries = pd.unique(training['Country'].to_numpy().ravel())
for country in unique_countries:
  filtered_df = training[(training['Country']==country)]
  country_rating = filtered_df['Rating'].values.mean()
  country_map[country] = country_rating

# Directors
directors_map = {}
directors_map[3] = 3

unique_directors = pd.unique(training[['Director1', 'Director2']].to_numpy().ravel())
for director in unique_directors:
  filtered_df = training[(training['Director1']==director) | (training['Director2']==director)]
  director_rating = filtered_df['Rating'].values.mean()
  directors_map[director] = director_rating

# Genres
genres_map = {}
genres_map[3] = 3

unique_genres = pd.unique(training[['Genre1', 'Genre2', 'Genre3']].to_numpy().ravel())
for genre in unique_genres:
  filtered_df = training[(training['Genre1']==genre) | (training['Genre2']==genre) | (training['Genre3']==genre)]
  genre_rating = filtered_df['Rating'].values.mean()
  genres_map[genre] = genre_rating

# Language
language_map = {}
language_map[3] = 3

unique_languages = pd.unique(training['Language'].to_numpy().ravel())
for language in unique_languages:
  filtered_df = training[(training['Language']==language)]
  language_rating = filtered_df['Rating'].values.mean()
  language_map[language] = language_rating

# Production_Company
company_map = {}
company_map[3] = 3

unique_companies = pd.unique(training['Production_Company'].to_numpy().ravel())
for company in unique_companies:
  filtered_df = training[(training['Production_Company']==company)]
  company_rating = filtered_df['Rating'].values.mean()
  company_map[company] = company_rating

# Writers
writers_map = {}
writers_map[3] = 3

unique_writers = pd.unique(training[['Writer1', 'Writer2']].to_numpy().ravel())
for writer in unique_writers:
  filtered_df = training[(training['Writer1']==writer) | (training['Writer2']==writer)]
  writer_rating = filtered_df['Rating'].values.mean()
  writers_map[writer] = writer_rating

In [12]:
# Convert object to value

def to_value(df, column, map_):
  array = df[column].to_numpy().ravel()
  result = list(map(lambda x: map_.setdefault(x, 3), array))

  return result

In [17]:
# Convert Training

for column in ['Actor1', 'Actor2','Actor3']:
  training[column] = to_value(training, column, actors_map)
training['Country'] = to_value(training, 'Country', country_map)
for column in ['Director1', 'Director2']:
  training[column] = to_value(training, column, directors_map)
for column in ['Genre1', 'Genre2', 'Genre3']:
  training[column] = to_value(training, column, genres_map)
training['Language'] = to_value(training, 'Language', language_map)
training['Production_Company'] = to_value(training, 'Production_Company', company_map)
for column in ['Writer1', 'Writer2']:
  training[column] = to_value(training, column, writers_map)

In [18]:
# Convert test

for column in ['Actor1', 'Actor2','Actor3']:
  test[column] = to_value(test, column, actors_map)
test['Country'] = to_value(test, 'Country', country_map)
for column in ['Director1', 'Director2']:
  test[column] = to_value(test, column, directors_map)
for column in ['Genre1', 'Genre2', 'Genre3']:
  test[column] = to_value(test, column, genres_map)
test['Language'] = to_value(test, 'Language', language_map)
test['Production_Company'] = to_value(test, 'Production_Company', company_map)
for column in ['Writer1', 'Writer2']:
  test[column] = to_value(test, column, writers_map)

In [21]:
training.to_pickle('converted_training.pkl')
test.to_pickle('converted_test.pkl')